openapi: 3.0.3
info:
  title: YumYumNow Delivery API
  description: YumYumNow Delivery
  version: 1.0.0
servers:
  - url: 'http://localhost:8081'
    description: 'Delivery Microservice'
paths:
  /delivery:
    post:
      summary: 'Create a delivery'
      description: 'Create a delivery based on order data'
      responses:
        '200':
          description: 'Successful response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'
        '400':
          description: 'Bad request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
  /delivery/{id}:
    get:
      summary: 'Get a delivery'
      description: 'Get delivery details based on id'
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: UUID of the delivery

      responses:
        '200':
          description: 'Successful response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'
        '400':
          description: 'Bad request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /delivery/{id}/updateStatus:
    post:
      summary: 'Update the status of a delivery'
      description: 'Update the status of a delivery. Vendors can set the status to ACCEPTED, REJECTED, PREPARING, GIVEN_TO_COURIER. Couriers can set the status to IN_TRANSIT, DELIVERED.'
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: UUID of the delivery
      responses:
        '200':
          description: 'Successful response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'
        '400':
          description: 'Bad request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              type: string
  /delivery/{id}/updateLocation:
    post:
      summary: "Update the location of the delivery"
      description: "Update the current location of the delivery (for couriers)"
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: UUID of the delivery
      responses:
        '200':
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'
        '400':
          description: 'Bad request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Location'
  /delivery/{id}/updateDeliveryTime:
    post:
      summary: "Update the delivery time"
      description: "Update estimatedDeliveryTime of an existing delivery (for couriers)"
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: UUID of the delivery
      responses:
        '200':
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'
        '400':
          description: 'Bad request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              type: string
  /delivery/{id}/accept:
    post:
      summary: 'Accept the delivery'
      description: 'Change the status of an existing delivery to ACCEPTED.'
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: UUID of the delivery
      responses:
        '200':
          description: 'Successful response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'
        '400':
          description: 'Bad request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Courier'
  /delivery/getAvailableInRadius:
    post:
      summary: 'Get available deliveries in radius (for couriers)'
      description: 'Get available deliveries in radius (for couriers). If a vendor has chosen to only deliver using its own couriers, then deliveries from that vendor will only be returned if the courier is affiliated with that vendor.'
      responses:
        '200':
          description: 'Successful response'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Delivery'
        '400':
          description: 'Bad request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              type: string
    
  /delivery/admin/maxDeliveryZone:
    post:
      summary: 'Set the default maximum delivery zone'
      description: 'Set the default maximum application-wide delivery zone for all vendors. This default value is used if a vendor has not specified the delivery zone.'
      responses:
        '200':
          description: 'Successful response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'
        '400':
          description: 'Bad request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              type: integer
    get:
      summary: 'Get the default maximum delivery zone'
      description: 'Get the default maximum application-wide delivery zone for all vendors. This default value is used if a vendor has not specified the delivery zone.'
      responses:
        '200':
          description: 'Successful response'
          content:
            application/json:
              schema:
                type: integer
                example: 200
        '400':
          description: 'Bad request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /delivery/admin/analytics:
    get:
      summary: 'Get delivery system analytics'
      description: 'Get delivery system analytics collected so far.'
      responses:
        '200':
          description: 'Successful response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Analytics'
        '400':
          description: 'Bad request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


components:
  schemas:
    Analytics:
      type: object
      properties:
        id:
          type: string
          example: "7ddf1042-8dfa-11ee-b9d1-0242ac120002"
        deliveries:
          type: array
          items:
            $ref: '#/components/schemas/Delivery'
        
    Order:
      type: object
      properties:
        id:
          type: string
          example: "7ddf136c-8dfa-11ee-b9d1-0242ac120002"
        customer:
          $ref: '#/components/schemas/Customer'
        vendor:
          $ref: '#/components/schemas/Vendor'
    Customer:
      type: object
      properties:
        id:
          type: string
          example: "7ddf1830-8dfa-11ee-b9d1-0242ac120002"
        name:
          type: string
          example: "Max Verstappen"
        deliveryAddress:
          type: string
          example: "Mekelweg 5, 2628 CD Delft"
        phone:
          type: string
          example: "+31 71 520 9291"
    Vendor:
      type: object
      properties:
        id:
          type: string
          example: "7ddf1a10-8dfa-11ee-b9d1-0242ac120002"
        name:
          type: string
          example: "John Smith"
        address:
          type: string
          example: "Professor Schermerhornstraat 19 2628 CN Delft"
        phone:
          type: string
          example: "+31 71 520 9297"
        allowsOnlyOwnCouriers:
          type: boolean
          example: true
        maxDeliveryZoneMeters:
          type: integer
          example: 150
    Location:
      type: object
      properties:
        timestamp: 
          type: string
          format: date-time
          example: "2018-12-10T13:49:51.141Z"
        latitude:
          type: number
          example: 10
        longitude:
          type: number
          example: 20
    Delivery:
      type: object
      properties:
        id:
          type: string
          example: "7ddf1b64-8dfa-11ee-b9d1-0242ac120002"
        order:
          $ref: '#/components/schemas/Order'
        courier:
          $ref: '#/components/schemas/Courier'
        status:
          type: string
          enum:
            - 'PENDING'
            - 'ACCEPTED'
            - 'REJECTED'
            - 'PREPARING'
            - 'GIVEN_TO_COURIER'
            - 'IN_TRANSIT'
            - 'DELIVERED'
          example: 'PREPARING'
        estimatedDeliveryTime:
          type: string
          format: date-time
          example: "2018-11-10T13:49:51.141Z"
        estimatedPreparationFinishTime:
          type: string
          format: date-time
          example: "2018-11-10T13:47:51.141Z"
        currentLocation:
          $ref: '#/components/schemas/Location'
    Error:
      type: object
      properties:
        code:
          type: integer
          example: 404
        message:
          type: string
          example: "Not Found"
    Courier:
      type: object
      properties:
        id:
          type: string
          example: "7ddf1c9a-8dfa-11ee-b9d1-0242ac120002"
        name:
          type: string
          example: "Sarah Johnson"
        phone:
          type: string
          example: "+31 71 524 9297"
        affiliatedVendor:
          $ref: '#/components/schemas/Vendor'